definitions:
  internal_example.CreateReq:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  internal_example.CreateResp:
    properties:
      name:
        type: string
    type: object
  internal_example.DeleteReq:
    properties:
      name:
        type: string
    type: object
  internal_example.DeleteResp:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  internal_example.EditReq:
    properties:
      name:
        type: string
    type: object
  internal_example.EditResp:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  internal_example.ListResp:
    properties:
      func:
        type: string
    type: object
  utl.RequestValidationError:
    properties:
      field:
        type: string
      message:
        type: string
      tag:
        type: string
    type: object
  utl.RequestValidationErrorResponse:
    properties:
      error_type:
        $ref: '#/definitions/utl.RequestValidationErrorType'
      errors:
        items:
          $ref: '#/definitions/utl.RequestValidationError'
        type: array
    type: object
  utl.RequestValidationErrorType:
    enum:
    - invalid_field
    type: string
    x-enum-varnames:
    - requestValidationErrorTypeInvalidField
host: localhost:8080
info:
  contact: {}
  description: STARTER_PLACEHOLDER
  title: STARTER_PLACEHOLDER
  version: 0.1.0
paths:
  /example:
    get:
      consumes:
      - application/json
      description: List
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_example.ListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utl.RequestValidationErrorResponse'
      summary: List
      tags:
      - example
    post:
      consumes:
      - application/json
      description: Create
      parameters:
      - description: Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_example.CreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_example.CreateResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utl.RequestValidationErrorResponse'
      summary: Create
      tags:
      - example
  /example/{id}:
    delete:
      consumes:
      - application/json
      description: Delete
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_example.DeleteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_example.DeleteResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utl.RequestValidationErrorResponse'
      summary: Delete
      tags:
      - example
    get:
      consumes:
      - application/json
      description: One
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_example.ListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utl.RequestValidationErrorResponse'
      summary: One
      tags:
      - example
    put:
      consumes:
      - application/json
      description: Edit
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/internal_example.EditReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_example.EditResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utl.RequestValidationErrorResponse'
      summary: Edit
      tags:
      - example
swagger: "2.0"
